# Replaces /usr/share/sway/config.d/60-bindings-screenshot.conf (same name).
# Screenshots go to the clipboard, with a notification.
bindsym {
    # Current output
    Print               exec grimshot --notify copy output
    # Focused window
    $mod+Print          exec grimshot --notify copy active
    # Click and drag an area
    $mod+Shift+Print    exec grimshot --notify copy area
}
